### ISSUE TITLE
error in bpay_mgr_hooks.php file

### ISSUE THREAD

**Issue by theozsnowman** [LEOPARD-host/BPAY-for-WHMCS#13]
error in the latest release on the bpay_mgr_hooks.php file

line 237

`$sql = "Select `userid` from `tblinvoices` where `id` = ".$var['invoiceid']."'";`

should be 

`$sql = "Select `userid` from `tblinvoices` where `id` = ".$var['invoiceid']."";`

**Comment by lsthompson** [comment]
Many thanks. I've modified this in the upcoming v2.2.1 release.

The release is delayed as I'm hopeful to resolve the cron issue.
