### ISSUE TITLE
concerns on new version?

### ISSUE THREAD

**Issue by theozsnowman** [LEOPARD-host/BPAY-for-WHMCS#19]
I just saw the new release and was about to upgrade but when looking at the new files it appears to remove the entire plugin admin functionality from the module?

is that correct?

do we now need to simply edit the settings directly in the modules hook file instead of via the admin?

just concerned as i dont want to break existing configurations

**Comment by lsthompson** [comment]
Hi Steve,

> do we now need to simply edit the settings directly in the modules hook file instead of via the admin?

That's correct - the code was more-or-less beyond help, so we're starting again slowly.

> just concerned as i don't want to break existing configurations

What in particular are you concerned about breaking?

ie. What would you like to see prioritised?

Thanks!
