### ISSUE TITLE
Image not generating

### ISSUE THREAD

**Issue by theozsnowman** [LEOPARD-host/BPAY-for-WHMCS#7]
Just updated the bPay module to this latest release (the old module was deleted, along with its database tables) and while it all installs correctly and seems to throw no errors its not generating either the preview image in the addon module settings page nor in the client profiles in the admin or on the invoices.

any ideas how to resolve?

Here are the environment details:

**File Permissions:**
File / Directory Name	File Type	Status	Permission Level	Action
/modules/gateways/bpay.php	PHP (Hypertext Preprocessor)	Found	0644	
/modules/gateways/bpay/arial.ttf	TTF (TrueType Font)	Found	0644	
bpay_mgr_hooks.php (Addon folder)	PHP (Hypertext Preprocessor)	Found	0644	
/includes/hooks/bpay_mgr_inc.php	PHP (Hypertext Preprocessor)	Found	0644	
Customers (Gateway folder)	Directory	Found	0755	
Invoices (Gateway folder)	Directory	Found	0755

**System Environment**
Environment Type	Result			
Operating System (OS)	Linux			
Web Server (Software)	Apache			
WHMCS Version	8.5.1			
IonCube Version	11...1			
BPAY Manager: Addon Version	2.1.9			
BPAY Manager: Hooks Version	2.1.9			
BPAY Gateway: Version	2.1.9

**Comment by theozsnowman** [comment]
also noted this error:

[04-Jul-2022 12:02:00 Australia/Melbourne] PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /home/accounts/public_html/modules/gateways/bpay.php on line 338

**Comment by lsthompson** [comment]
Thanks for this, Steve. Could you please confirm a few things:

1. Operating System & version?
2. Apache version you're running?
3. PHP version in-use on the site?

If you enable display_errors, are you seeing anything thrown on-page (on any impacted page)?

**Comment by lsthompson** [comment]
Also Steve, could you please clarify on which v2.1.9 you're running? There are 2 it could be:

1. https://github.com/lsthompson/BPAY-for-WHMCS/releases/tag/v2.1.9 (the last RH release, tagged/zipped)
2. https://github.com/lsthompson/BPAY-for-WHMCS/tree/master (which is WIP, and still reporting as 2.1.9)

If you're on the former, please update to the master branch and let me know if it's still faulty in all locations.

The [version](https://github.com/lsthompson/BPAY-for-WHMCS/blob/master/version) file will be updated once the key bugs have been ironed out. Looking forward to hearing back.
