### ISSUE TITLE
Delayed Image Generation - Invoice sans-image then OK - by Invoice #

### ISSUE THREAD

**Issue by bakkbone** [LEOPARD-host/BPAY-for-WHMCS#9]
Hi team

Not sure if this is behaviour as intended or otherwise

If method is via invoice number rather than via customer number, the invoice doesn't have the BPAY image when first sent (eg. automatically sent), but does have it if re-sent subsequently. I believe it's generating the BPAY image *after* the cron sends the invoice

File Permissions
File / Directory Name	File Type	Status	Permission Level	Action
/modules/gateways/bpay.php	PHP (Hypertext Preprocessor)	Found	0644	
/modules/gateways/bpay/arial.ttf	TTF (TrueType Font)	Found	0644	
bpay_mgr_hooks.php (Addon folder)	PHP (Hypertext Preprocessor)	Found	0644	
/includes/hooks/bpay_mgr_inc.php	PHP (Hypertext Preprocessor)	Found	0644	
Customers (Gateway folder)	Directory	Found	0755	
Invoices (Gateway folder)	Directory	Found	0755	

System Environment
Environment Type	Result			
Operating System (OS)	Linux			
Web Server (Software)	Apache			
WHMCS Version	8.5.1			
IonCube Version	12...2			
BPAY Manager: Addon Version	2.1.9			
BPAY Manager: Hooks Version	2.1.9			
BPAY Gateway: Version	2.1.9

PHP 7.4 running on Ubuntu 20.04

**Comment by lsthompson** [comment]
Thanks for flagging this. I'm yet to take a look for you.

With projects at the moment, it could be a little while yet. Appreciate your patience.

**Comment by lsthompson** [comment]
In terms of automation, there's a hook registered for the InvoiceCreation point which fires `invoiceCreated`.

`add_hook("InvoiceCreation",1,"invoiceCreated");`

`invoiceCreated` in turn fires `createCRN` which in turn fires `generateBpayRef` - and the CRN is stored in the DB.

However it's `insertInvoiceFunc` which injects the BPAY Reference image JPG code into the invoicepdf.tpl file.
It does that by calling `BPAY_PDF` in the gateway code, and this is ultimately where we find `generateImage`.

So it seems that it is to do with timing as you suspected. Hook is fired, and BPAY Manager makes a ref.
During that Invoice Creation process, it sends the email out, trying to get a BPAY JPG as it does.

Currently the hook firing sequence looks like: `invoiceCreated` > `createCRN` > `generateBpayRef`

I suspect this would be resolved if we amended the `invoiceCreated` function to also call `generateImage`.

**Comment by lsthompson** [comment]
I no longer think this is to do with time-of-execution as first thought, but rather about _template selection based on invocation method_. There are good odds it is due to _cron vs admin-invoked_ invoice sending, as all re-sends do work.

The `/templates/invoicepdf.tpl` file seems to be used if cron-invoked, but `/templates/your_template/invoicepdf.tpl` is used if it's admin-invoked. We're pushing another release which will make sure that file is also injected with BPAY code.

In the interim we're waiting for tomorrow's daily cron to confirm whether cron-issued invoices contain the BPAY image.

**Comment by lsthompson** [comment]
We couldn't verify this as being separate to Issue #1 due to what I've explained above. Closing as duplicate.
